title: Is this MWE really 'working'?
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://koengr.github.io/mwe

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
